### ISSUE TITLE
Latest androidx.* and msal1.0.0 updates

### ISSUE THREAD

**Issue by Mohamed-Ibrahim-6b** [microsoftgraph/msgraph-training-android#24]
Hi Jason,

First of all many thanks for this tutorial and also for the last updates. Here  are some issues I found as I was updating my app:

**Chapter 2: Create an Android app**

_Section: Add fragments, step 9_
3 imports need to be updated for androidx (namely, `NonNull`, `Nullable` and `Fragment`)

**Chapter 3: Add Azure AD authentication**

_Section: Implement sign-in, step 9_
The note at the end of this step needs to be changed

_Section: Get user details, step 7_
The argument in `onSuccess()` method needs to be of type `IAuthenticationResult` not `AuthenticationResult`

**Chapter 4: Get calendar data**

_Section: Get calendar events, step 3_
The note at the end of this step has a ">" in the middle of the second bullet point. I don't know if this is intentional or just a typo.

After dealing with these issues the app works well.

All the best
Mohamed

**Comment by jasonjoh** [comment]
Thanks, I'll take a look.
