### ISSUE TITLE
Access is denied. Check credentials and try again.

### ISSUE THREAD

**Issue by rital-naik-adrosonic** [microsoftgraph/msgraph-training-android#29]
While fetching emails for  mClient!!.me().mailFolders().buildRequest()[callback]  call  i am getting following error log

com.microsoft.graph.http.GraphServiceException: Error code: ErrorAccessDenied
    Error message: Access is denied. Check credentials and try again.
    
    GET https://graph.microsoft.com/v1.0/me/mailFolders
    SdkVersion : graph-java-v1.4.0
    Authorization : Bearer eyJ0eXAiOiJKV1QiLCJub25jZSI6InFzTDN2NklER0I0UUZ4bVBqbkNFdFVKUENJYkxXRU9MWGJLRlRwOUQ3ZFEiLCJhbGciOiJSUzI1NiIsIng1dCI6InBpVmxsb1FEU01LeGgxbTJ5Z3FHU1ZkZ0ZwQSIsImtpZCI6InBpVmxsb1FEU01LeGgxbTJ5Z3FHU1ZkZ0ZwQSJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC83MmJjNTNjNC02MjJkLTRjYmItODdhOS1hYjM3OTkxMmI0MDYvIiwiaWF0IjoxNTgwMjgxNjE5LCJuYmYiOjE1ODAyODE2MTksImV4cCI6MTU4MDI4NTUxOSwiYWNjdCI6MCwiYWNyIjoiMSIsImFpbyI6IjQyTmdZSmpMUDlYc1NkU2x3LzhjNXplYVNZVDJQSXFKc21jKzN0VHo2NEdaL1FwWEZ6NEEiLCJhbXIiOlsicHdkIl0sImFwcF9kaXNwbGF5bmFtZSI6Iktub3dsZWRlbWlsbCBNb2JpbGUgQXBwIiwiYXBwaWQiOiJmNjI1OTk0Yi00MWJmLTRhNzMtOWIzOC05MDAzZTg4OWQyOWQiLCJhcHBpZGFjciI6IjAiLCJmYW1pbHlfbmFtZSI6IlNhbXVlbCIsImdpdmVuX25hbWUiOiJTdGVwaGVuIiwiaXBhZGRyIjoiNDkuMjQ4LjE0OC4yMDIiLCJuYW1lIjoiU3RlcGhlbiBTYW11ZWwiLCJvaWQiOiIwM2M3MjhjNi01NWFiLTRjMDktOGQzYy1iOTVjYmMyNWYwY2YiLCJwbGF0ZiI6IjEiLCJwdWlkIjoiMTAwMzNGRkY5QUYzOTM1RiIsInNjcCI6IkNhbGVuZGFycy5SZWFkIG9wZW5pZCBwcm9maWxlIFVzZXIuUmVhZCBlbWFpbCIsInNpZ25pbl9zdGF0ZSI6WyJrbXNpIl0sInN1YiI6IjVFUWF5bi16X2FvMU5YWXJPWjV3N1p2emkwX2pMNGxTZlJYSDQ4bzlUZ3ciLCJ0aWQiOiI3MmJjNTNjNC02MjJkLTRjYmItODdhOS1hYjM3OTkxMmI0MDYiLCJ1bmlxdWVfbmFtZSI6InN0ZXBoZW4uc2FtdWVsQGFkcm90ZXN0c2VydmVyLmNvbSIsInVwbiI6InN0ZXBoZW4uc2FtdWVsQGFkcm90ZXN0c2VydmVyLmNvbSIsInV0aSI6Im9YbUFJVy1hbUVtMHpXRzUzdkVhQVEiLCJ2ZXIiOiIxLjAiLCJ4bXNfc3QiOnsic3ViIjoiZWEwRmNwbER3WC05Z1pmb3V6QUZhV2JiM2gyUXVSVjlkMm5KaF9HdDFSbyJ9LCJ4bXNfdGNkdCI6MTQ1OTc3OTA2OH0.bwdBq8UiU17vVxDycIqZgLQ2_RKBEMIi3r8D5EPI-xe2agjdu7EcSClOU4bGdMU4314pQvmOigJ0dVY67f4QrNv7Oc_QZSXhxLP01BVcqj3I6gDt9Xw6f0HglRR3Jw4v8pyF7LefgMvNjnW8oN-cs3iS4homyTxOisIqJwb3Dbmbazx9psA5rt-OtXCdYKb3xWx9g9TM7uFZmV_cnl9r24NPRzxzwEmap8H8HfrZgzobnlhb5gXWJTOVXlmq6ANeoVaLtsPEkSbKZZg5l_820gl_KsSE-LMKTzS1PoVy5tBpr42I00h3G15HC05EXCNxYIsZBZ6rPl-TGHidQNv1-g
    
    
    403 : Forbidden
    X-Android-Selected-Protocol : http/1.1
    Strict-Transport-Security : max-age=31536000
    Cache-Control : private
    x-ms-ags-diagnostic : {"ServerInfo":{"DataCenter":"South India","Slice":"SliceC","Ring":"3","ScaleUnit":"000","RoleInstance":"AGSFE_IN_3"}}
    client-request-id : 021478ab-8f0c-45cb-9d7a-b7455718a859
    X-Android-Response-Source : NETWORK 403
    X-Android-Sent-Millis : 1580281922991
    request-id : 021478ab-8f0c-45cb-9d7a-b7455718a859
    Content-Length : 253
    X-Android-Received-Millis : 1580281923076
    Date : Wed, 29 Jan 2020 07:12:00 GMT
    Content-Type : application/json
    {
      "error": {
        "code": "ErrorAccessDenied",
        "message": "Access is denied. Check credentials and try again.",
        "innerError": {
          "request-id": "021478ab-8f0c-45cb-9d7a-b7455718a859",
          "date": "2020-01-29T07:12:01"
        }
      }
    }
    
        at com.microsoft.graph.http.DefaultHttpProvider.handleErrorResponse(DefaultHttpProvider.java:388)
        at com.microsoft.graph.http.DefaultHttpProvider.sendRequestInternal(DefaultHttpProvider.java:321)
        at com.microsoft.graph.http.DefaultHttpProvider.send(DefaultHttpProvider.java:204)
        at com.microsoft.graph.http.DefaultHttpProvider.send(DefaultHttpProvider.java:184)
        at com.microsoft.graph.http.BaseCollectionRequest.send(BaseCollectionRequest.java:87)
        at com.microsoft.graph.requests.extensions.MailFolderCollectionRequest.get(MailFolderCollectionRequest.java:52)
        at com.microsoft.graph.requests.extensions.MailFolderCollectionRequest$1.run(MailFolderCollectionRequest.java:43)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

**Comment by jasonjoh** [comment]
This sample does not fetch mail folders, and does not request the appropriate permissions to be able to fetch mail folders. It sounds like you've modified the app but not added the required scopes. You need one of the following: `Mail.ReadBasic`, `Mail.Read`, `Mail.ReadWrite`.

**Comment by rital-naik-adrosonic** [comment]
Hi there, Thanks for quick response,

Yes I have modified the app, and trying to fetch mailfolders. Could you please post all the possible list of scope

**Comment by jasonjoh** [comment]
The easiest way is to check the doc for the API call you're trying to use, it tells you the scopes needed.

https://docs.microsoft.com/graph/api/user-list-mailfolders?view=graph-rest-1.0

For a list of all scopes, you can check https://docs.microsoft.com/graph/permissions-reference?context=graph%2Fapi%2F1.0&view=graph-rest-1.0

**Comment by jasonjoh** [comment]
@rital-naik-adrosonic did you get this figured out?

**Comment by rital-naik-adrosonic** [comment]
Hi @jasonjoh  after adding my API call to asynctask, request got called successfully. Just few min back my colleague tried the approach n it worked
