### ISSUE TITLE
Trust anchor for certification path not found in Microsoft Graph API

### ISSUE THREAD

**Issue by arunsankar8** [microsoftgraph/msgraph-training-android#44]
I have been using the Microsoft Graph API in my android application to get the calendar events etc... The Authentication and events data retrieval were all working fine, but Microsoft Graph is not working properly on devices under 4.4 lately, when I try to get user data or calendar events, an exception occurs. I run the same codes on 2 android SDK versions, on 6.0, I can get all the data I want but on 4.4, it fails with the exception :

`Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.`

(The Microsoft Graph were working fine on devices under 4.4 till last December but it stopped giving the following exception)

These are the libraries that are used now

```
implementation 'com.microsoft.identity.client:msal:2.0.5'
implementation 'com.microsoft.graph:microsoft-graph:2.5.0'

implementation 'com.squareup.retrofit2:converter-gson:2.9.0'
implementation("com.squareup.retrofit2:retrofit:2.9.0")

implementation("com.squareup.okhttp3:okhttp:3.12.8") {
force = true
}

implementation "com.squareup.okhttp3:logging-interceptor:3.12.8"
```

**Comment by jasonjoh** [comment]
@arunsankar8 you should open an issue on the SDK's repository. This tutorial was never tested on 4.4.

https://github.com/microsoftgraph/msgraph-sdk-java
