### ISSUE TITLE
About using Microsoft graph to build Android apps, the class in the example was not found

### ISSUE THREAD

**Issue by saosirse** [microsoftgraph/msgraph-training-android#54]
According to official documents（ https://docs.microsoft.com/zh-cn/graph/tutorials/android?context=outlook%2Fcontext ）Use Microsoft graph to build Android applications.

However, when I write code according to the examples in the document, I find that some classes cannot be found in the corresponding packages, such as com.microsoft.graph.authentication.baseauthenticationprovider, which cannot be found in packages that depend on Microsoft graph: 3.1.0, and com.microsoft.graph.options cannot be found.

Is there a problem with the document sample code? Or do I rely on the wrong package? (I checked other versions of packages on GitHub and found no relevant classes)

**Comment by jasonjoh** [comment]
No those classes should exist (See [BaseAuthenticationProvider.java](https://github.com/microsoftgraph/msgraph-sdk-java-core/blob/874797bdc065c25970f21ca24e40e324d49e3afd/src/main/java/com/microsoft/graph/authentication/BaseAuthenticationProvider.java)). You may have some issue with your classpath?

**Comment by saosirse** [comment]
Thank you. My problem has been solved through your help.

**Comment by saosirse** [comment]
@jasonjoh 
Sorry, I opened this issue again.
I want to confirm one thing to you,
The classes you provided me are included in the msgraph-sdk-java-core package,
I rely on the following items in build.gradle according to the demo:
implementation 'com. google. android. material:material:1.3. 0'
implementation 'com. microsoft. identity. client:msal:2.0. 8'
implementation ('com.microsoft.graph:microsoft-graph:3.1.0') {
exclude group: 'javax.activation'
}
Will they automatically rely on msgraph-sdk-java-core?
（All the packages I need in my project are imported one by one）

**Comment by jasonjoh** [comment]
Yes. msgraph-sdk-java-core is a dependency of microsoft-graph.

https://github.com/microsoftgraph/msgraph-sdk-java/blob/8d3e43c62c05054bc9c530fe64fd6aedcbda2058/pom.xml#L35-L39

Not sure what you mean by "imported one by one by myself"?

**Comment by jasonjoh** [comment]
Great - sounds like you have what you need then, so I'll close this.
